# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.jwtsecret: '%env(JWT_SECRET)%'
    documents_eleves_directory: '%kernel.project_dir%/public/uploads/eleves/documents'
    documents_personnel_directory: '%kernel.project_dir%/public/uploads/personnels/documents'
    documents_administration_directory: '%kernel.project_dir%/public/administration/documents'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Service\OpenAIService:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'
            $httpClient: '@http_client'
            
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\cerclesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Cercles'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Cercles'}    # add more service definitions when explicit configuration is needed
    App\EventListener\communesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Communes'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Communes'}    # add more service definitions when explicit configuration is needed
    App\EventListener\departementsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Departements'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Departements'}    # add more service definitions when explicit configuration is needed
    App\EventListener\nomsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Noms'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Noms'}    # add more service definitions when explicit configuration is needed
    App\EventListener\prenomsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Prenoms'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Prenoms'}    # add more service definitions when explicit configuration is needed
    App\EventListener\professionsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Professions'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Professions'}    # add more service definitions when explicit configuration is needed
    App\EventListener\regionsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Regions'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Regions'}    # add more service definitions when explicit configuration is needed
    App\EventListener\statutElevesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Statuts'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Statuts'}    # add more service definitions when explicit configuration is needed
    App\EventListener\usersEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Users'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Users'}    # add more service definitions when explicit configuration is needed
    App\EventListener\ninasEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Ninas'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Ninas'}    # add more service definitions when explicit configuration is needed
    App\EventListener\telephonesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Telephones1'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Telephones1'}    # add more service definitions when explicit configuration is needed
    App\EventListener\DisableForeignKeyConstraintsListener:
        tags:
            - { name: doctrine.event_listener, event: preFlush }
            - { name: doctrine.event_listener, event: postFlush }
    App\EventListener\classesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Classes'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Classes'}    # add more service definitions when explicit configuration is needed
    App\EventListener\niveauxEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Niveaux'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Niveaux'}    # add more service definitions when explicit configuration is needed
    App\EventListener\cyclesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Cycles'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Cycles'}    # add more service definitions when explicit configuration is needed
    App\EventListener\etablissementsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Etablissements'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Etablissements'}    # add more service definitions when explicit configuration is needed
    App\EventListener\enseignementsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Enseignements'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Enseignements'}    # add more service definitions when explicit configuration is needed
    App\EventListener\parentsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Parents'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Parents'}    # add more service definitions when explicit configuration is needed
    App\EventListener\elevesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Eleves'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Eleves'}    # add more service definitions when explicit configuration is needed
    App\EventListener\peresEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Peres'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Peres'}    # add more service definitions when explicit configuration is needed
    App\EventListener\meresEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Meres'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Meres'}    # add more service definitions when explicit configuration is needed
    App\EventListener\telephones2EntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Telephones2'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Telephones2'}    # add more service definitions when explicit configuration is needed
    App\EventListener\anneeScolairesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\AnneeScolaires'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\AnneeScolaires'}    # add more service definitions when explicit configuration is needed
    App\EventListener\caissesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Caisses'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Caisses'}    # add more service definitions when explicit configuration is needed
    App\EventListener\departsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Departs'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Departs'}    # add more service definitions when explicit configuration is needed
    App\EventListener\detailcaissesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\DetailsCaisses'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\DetailsCaisses'}    # add more service definitions when explicit configuration is needed
    App\EventListener\dossierElevesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\DossierEleves'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\DossierEleves'}    # add more service definitions when explicit configuration is needed
    App\EventListener\echeancesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Echeances'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Echeances'}    # add more service definitions when explicit configuration is needed
    App\EventListener\ecoleProvenancesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\EcoleProvenances'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\EcoleProvenances'}    # add more service definitions when explicit configuration is needed
    App\EventListener\fraisScolairesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\FraisScolaires'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\FraisScolaires'}    # add more service definitions when explicit configuration is needed
    App\EventListener\fraisTypeEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\FraisTypes'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\FraisTypes'}    # add more service definitions when explicit configuration is needed
    App\EventListener\lieuNaissancesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\LieuNaissances'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\LieuNaissances'}    # add more service definitions when explicit configuration is needed
    App\EventListener\scolarites1EntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Scolarites1'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Scolarites1'}    # add more service definitions when explicit configuration is needed
    App\EventListener\scolarites2EntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Scolarites2'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Scolarites2'}    # add more service definitions when explicit configuration is needed

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
